spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        show-sql: ${SPRING_JPA_SHOW_SQL:true}
        open-in-view: false
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
